"""0812

Revision ID: 00416243153c
Revises: 382a3c1d4d48
Create Date: 2025-08-12 11:53:50.683348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00416243153c'
down_revision: Union[str, None] = '382a3c1d4d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_groups', sa.Text(), nullable=False, comment='问题组'),
    sa.Column('question', sa.Text(), nullable=False, comment='问题描述'),
    sa.Column('question_content', sa.Text(), nullable=False, comment='问题内容'),
    sa.Column('answer', sa.ARRAY(sa.String()), nullable=False, comment='答案选项'),
    sa.Column('answer_extreme', sa.ARRAY(sa.String()), nullable=True, comment='答案两端倾向'),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='维度权重'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_questionnaire',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False, comment='用户ID'),
    sa.Column('evaluate_id', sa.String(), nullable=False, comment='问卷项ID'),
    sa.Column('answer', sa.String(), nullable=True, comment='用户答案'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_evaluate')
    op.drop_table('evaluate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluate',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question_groups', sa.TEXT(), autoincrement=False, nullable=False, comment='问题组'),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False, comment='问题描述'),
    sa.Column('answer', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False, comment='答案选项'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('question_content', sa.TEXT(), autoincrement=False, nullable=False, comment='问题内容'),
    sa.Column('answer_extreme', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True, comment='答案两端倾向'),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='维度权重'),
    sa.PrimaryKeyConstraint('id', name='evaluate_pkey')
    )
    op.create_table('user_evaluate',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('evaluate_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='评估ID'),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True, comment='用户答案'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_evaluate_pkey')
    )
    op.drop_table('user_questionnaire')
    op.drop_table('questionnaire')
    # ### end Alembic commands ###
