"""user

Revision ID: 0aecf439e393
Revises: dff58f255bdc
Create Date: 2025-08-01 16:58:56.091041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aecf439e393'
down_revision: Union[str, None] = 'dff58f255bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('union_id', sa.String(), nullable=True, comment='微信唯一id'),
    sa.Column('nickname', sa.String(), nullable=True, comment='昵称'),
    sa.Column('birth_year', sa.Integer(), nullable=True, comment='出生年'),
    sa.Column('gender', sa.Integer(), nullable=True, comment='0男/1女'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
