"""0815

Revision ID: 27b11ad243c9
Revises: 37963b57c3fb
Create Date: 2025-08-15 06:29:24.244044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b11ad243c9'
down_revision: Union[str, None] = '37963b57c3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dimensional',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False, comment='用户ID'),
    sa.Column('dimensional', sa.String(), nullable=False, comment='维度'),
    sa.Column('score', sa.Numeric(precision=4, scale=1), nullable=False, comment='分数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questionnaire_group', sa.Column('sub_name', sa.String(), nullable=True, comment='子组名'))
    op.add_column('questionnaire_group', sa.Column('sub_name_en', sa.String(), nullable=True, comment='子组名英文'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire_group', 'sub_name_en')
    op.drop_column('questionnaire_group', 'sub_name')
    op.drop_table('user_dimensional')
    # ### end Alembic commands ###
