"""0812-1

Revision ID: 2a59cb931f97
Revises: 00416243153c
Create Date: 2025-08-12 12:05:27.065690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a59cb931f97'
down_revision: Union[str, None] = '00416243153c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_questionnaire', sa.Column('questionnaire_id', sa.String(), nullable=False, comment='问卷项ID'))
    op.drop_column('user_questionnaire', 'evaluate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_questionnaire', sa.Column('evaluate_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='问卷项ID'))
    op.drop_column('user_questionnaire', 'questionnaire_id')
    # ### end Alembic commands ###
