"""userPrompt

Revision ID: 3541a20b5a54
Revises: 0aecf439e393
Create Date: 2025-08-04 16:07:44.973724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3541a20b5a54'
down_revision: Union[str, None] = '0aecf439e393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_prompt',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True, comment='用户id'),
    sa.Column('prompt', sa.Text(), nullable=True, comment='人设'),
    sa.Column('title', sa.String(), nullable=True, comment='标题'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_prompt')
    # ### end Alembic commands ###
