"""0813-2

Revision ID: 37963b57c3fb
Revises: 61c0a39618e1
Create Date: 2025-08-13 15:19:51.124778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37963b57c3fb'
down_revision: Union[str, None] = '61c0a39618e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_group', sa.Column('sort', sa.Integer(), nullable=True, comment='排序'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire_group', 'sort')
    # ### end Alembic commands ###
