"""init

Revision ID: 382a3c1d4d48
Revises: 
Create Date: 2025-08-06 14:02:42.884232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382a3c1d4d48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_client',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False, comment='API Key'),
    sa.Column('base_url', sa.String(), nullable=False, comment='api域名'),
    sa.Column('proxy', sa.String(), nullable=True, comment='代理'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('ai_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True, comment='类型 user/asst'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qw_access_token',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.String(), nullable=False, comment='企业微信Token'),
    sa.Column('expires_in', sa.Integer(), nullable=False, comment='过期时长/s'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_prompt',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True, comment='用户id'),
    sa.Column('prompt', sa.Text(), nullable=True, comment='人设'),
    sa.Column('title', sa.String(), nullable=True, comment='标题'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True, comment='手机号'),
    sa.Column('passwd', sa.String(), nullable=True, comment='密码'),
    sa.Column('union_id', sa.String(), nullable=True, comment='微信唯一id'),
    sa.Column('nickname', sa.String(), nullable=True, comment='昵称'),
    sa.Column('birth_year', sa.Integer(), nullable=True, comment='出生年'),
    sa.Column('gender', sa.Integer(), nullable=True, comment='0男/1女'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_prompt')
    op.drop_table('qw_access_token')
    op.drop_table('ai_session')
    op.drop_table('ai_client')
    # ### end Alembic commands ###
