"""0813

Revision ID: 47806fc61c90
Revises: 5ff5c22ff7d3
Create Date: 2025-08-13 11:36:36.488615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47806fc61c90'
down_revision: Union[str, None] = '5ff5c22ff7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_group',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='组名'),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='维度权重'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('questionnaire', sa.Column('group_id', sa.String(), nullable=True, comment='问题组ID'))
    op.add_column('questionnaire', sa.Column('sort', sa.Integer(), nullable=True, comment='排序'))
    op.drop_column('questionnaire', 'weights')
    op.drop_column('questionnaire', 'question_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire', sa.Column('question_groups', sa.VARCHAR(), autoincrement=False, nullable=True, comment='问题组'))
    op.add_column('questionnaire', sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='维度权重'))
    op.drop_column('questionnaire', 'sort')
    op.drop_column('questionnaire', 'group_id')
    op.drop_table('questionnaire_group')
    # ### end Alembic commands ###
