"""prompt

Revision ID: 4f231af985a2
Revises: dc7b24f88f5d
Create Date: 2025-08-07 16:53:08.147976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f231af985a2'
down_revision: Union[str, None] = 'dc7b24f88f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True, comment='人设'),
    sa.Column('title', sa.String(), nullable=True, comment='标题'),
    sa.Column('state', sa.String(), nullable=True, comment='状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompts')
    # ### end Alembic commands ###
