"""question_content

Revision ID: 5504397897dd
Revises: 27e1d263fe35
Create Date: 2025-08-08 16:37:58.789452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5504397897dd'
down_revision: Union[str, None] = '27e1d263fe35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluate', sa.Column('question_content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluate', 'question_content')
    # ### end Alembic commands ###
