"""0812-2

Revision ID: 5ff5c22ff7d3
Revises: 2a59cb931f97
Create Date: 2025-08-12 12:10:45.863610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff5c22ff7d3'
down_revision: Union[str, None] = '2a59cb931f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionnaire', 'question_groups',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_comment='问题组',
               existing_nullable=False)
    op.alter_column('questionnaire', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_comment='问题描述',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questionnaire', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_comment='问题描述',
               existing_nullable=False)
    op.alter_column('questionnaire', 'question_groups',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_comment='问题组',
               existing_nullable=False)
    # ### end Alembic commands ###
