"""0813-1

Revision ID: 61c0a39618e1
Revises: 47806fc61c90
Create Date: 2025-08-13 12:27:37.181098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c0a39618e1'
down_revision: Union[str, None] = '5b1c795bcb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_dimensional', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=4, scale=1),
               existing_comment='分数',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_dimensional', 'score',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='分数',
               existing_nullable=False)
    # ### end Alembic commands ###
