"""uodate_userPrompt

Revision ID: dc7b24f88f5d
Revises: 382a3c1d4d48
Create Date: 2025-08-07 15:36:16.404666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7b24f88f5d'
down_revision: Union[str, None] = '382a3c1d4d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_prompt', sa.Column('state', sa.String(), nullable=True, comment='状态'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_prompt', 'state')
    # ### end Alembic commands ###
