"""ai session & client

Revision ID: dff58f255bdc
Revises: 60aed912de00
Create Date: 2025-07-28 17:50:53.897792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff58f255bdc'
down_revision: Union[str, None] = '60aed912de00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_client',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False, comment='API Key'),
    sa.Column('base_url', sa.String(), nullable=False, comment='api域名'),
    sa.Column('proxy', sa.String(), nullable=True, comment='代理'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('ai_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ASST', 'USER', name='sessionrole'), nullable=True, comment='类型 user/asst'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_session')
    op.drop_table('ai_client')
    # ### end Alembic commands ###
